Reinstall python modules if Django missing
Improve checks for reinstalling python modules:

- If Django is missing, always reinstall
- Always reinstall all dependencies, even if they exist (in case some of them might be broken)

diff --git a/bin/update-requirements b/bin/update-requirements
--- a/bin/update-requirements
+++ b/bin/update-requirements
@@ -24,3 +24,7 @@ if [ -f requirements/dev.txt ]; then
 else
   echo "Warning: No requirements file found at $REQUIREMENTS_PATH. Not installing requirements." >> /dev/stderr
 fi
+
+if ! python -c "import django"; then
+  echo "Error: Django not found."
+fi
